FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model_training/ /app/model_training/
COPY backend/ /app/

EXPOSE 8000

CMD ["python", "main.py"]
